/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amlogic_graphics_DecoderInfo */

#ifndef _Included_com_amlogic_graphics_DecoderInfo
#define _Included_com_amlogic_graphics_DecoderInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
