/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test */
#ifndef _Included_com_amlogic_OOBE
#define _Included_com_amlogic_OOBE
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_amlogic_OOBE_SetPpm_setPpmDispJni
  (JNIEnv *, jobject ,jint ,jint);
    
#ifdef __cplusplus
}
#endif
#endif