#!/system/bin/sh

if [ -e /data/data/.wifiidle ]; then
	exit
fi

if [ -e /data/data/com.android.providers.settings/databases/settings.db ]; then
	sqlite3 /data/data/com.android.providers.settings/databases/settings.db "insert into secure values(null, 'wifi_idle_ms', '180000');"
	touch /data/data/.wifiidle
fi
